[CORE-9689] Add support for absolute url redirect
goodhood-eu/react-router-manager pull request #12
Opened 2022-04-13 12:49 UTC by iamuchejude

https://jira.nebenan.de/browse/CORE-9689

2022-04-13 12:53 UTC, inomn commented on package.json
> +  "version": "3.2.3-beta.0",
looks more like a new feature, go with 3.3.0?

2022-04-13 12:54 UTC, eliasbraun requested changes

2022-04-13 12:55 UTC, inomn commented on src/render.jsx
> +  window.location.replace(to);
what about SSR?

2022-04-13 13:26 UTC, peterhass commented on src/utils.jsx
> +export const isAbsoluteUrl = (url) => url && url.startsWith('http');
No, absolute url needs to match url spec schema 100%

schema://host/path?query etc

But another thing: Better to check for http:// and https:// to not get into weird cases with weird route names

2022-04-22 10:41 UTC, closed without merging

2022-04-22 10:41 UTC, inomn commented
We don't need it anymore